### ISSUE TITLE
Mercury fails to save to db

### ISSUE THREAD

**Issue by bjhaid** [jejacks0n/mercury#144]
Mercury was working fine, but really I cant tell when and where in broke in my app, I keep getting "mercury was unable to save to the url" I realised that it was updating a record that had the following:

<a style="display: none;" href="/editor/pages/2" data-save-url="/pages/2/mercury_update" id="edit_link">Edit Foo</a>

when I append this to some other records, then saving works, I am getting confused here, I would have included the dirty hack, but the app is in production already, and Mercury breaks both in development and production.

Awaiting your response, thanks

**Comment by rkrevolution** [comment]
This is still an issue for me... can you please post how you solved it?
