### ISSUE TITLE
POST_INSTALL

### ISSUE THREAD

**Issue by wedr** [jejacks0n/mercury#185]
Hi,
when can´t install mercury because when I´m intalling it, everytime says

Could not find "POST_INSTALL" in any of your source paths. Your current so
paths are:
C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/mercury-rails-0.3.1

Can you help me?

**Comment by cevaris** [comment]
Confirmed @jejacks0n suggestion worked for me, adding the following to my Gemfile.

`gem 'mercury-rails', git: 'git://github.com/jejacks0n/mercury.git', tag: 'v0.9.0'`
