### ISSUE TITLE
Does mercury support kaminari and carrierwave?

### ISSUE THREAD

**Issue by richarddong** [jejacks0n/mercury#232]
Docs said mercury supports will_paginate and paperclip.

What about [kaminari](https://github.com/amatsuda/kaminari) and [carrierwave](https://github.com/jnicklas/carrierwave)?

**Comment by shilpi230** [comment]
I want to use carrier wave in mercury as i am integrating it with my rails app where i have already used carrier wave so it will be easy for me to integrate i have done ```mercury:install:image``` and got the image_controller but how do i put it into views so that it will go to carrier wave ?

**Comment by jejacks0n** [comment]
read about carrierwave?

**Comment by shilpi230** [comment]
yes i am good with carrierwave but how do i tell mercury to go to carrierwave uploader?
