### ISSUE TITLE
Trouble storing images on heroku

### ISSUE THREAD

**Issue by webdesserts** [jejacks0n/mercury#252]
I am having issues getting images to store on Heroku. When I initially upload the images everything seems to work. But everytime I push to heroku the images go missing. I thought this was possibly an issue with my `.gitignore`, but i'm a little confused because when I `heroku run bash` and look in my `/public` directory there is no system folder. This is despite the fact that the image at that time appears in the browser. I've checked the database and all the images records are stored, I just don't know what's happening with the image files they reference. 

My project can be found here [on github](https://github.com/mcmullins/CTCC) if you want to look.

**Comment by NidhalSghairi** [comment]
i think that heroku doesn't accept png images .so if you have png images convert them to jpg
