### ISSUE TITLE
Save URL Changing when loading

### ISSUE THREAD

**Issue by deanchester** [jejacks0n/mercury#267]
I've followed the RailsCast as best I could (running rails 3.2.8) using the latest commit in the repo, but my changes aren't being saved. I added an alert to output the URL to which it was saving as it was not appearing in the rails console log. And I noticed that the Alert box was appearing twice, once with the URL as it should be the next it would be blank. So what is going wrong.  Here is what the ready function looks like: 
$(window).bind('mercury:ready', function() {
  var link = $('#mercury_iframe').contents().find('#edit_link');
  Mercury.saveURL = link.data('save-url');
  alert(Mercury.saveURL); // Line I added to see whether the URL was correct. 
  link.hide();
});

**Comment by betacanis** [comment]
Add the following javascript snippet to your rails template
<script>
function onMercuryReady() { Mercury.saveUrl = '/pages/' + <%= @page.id %> +"/mercury_update"; };
</script>

**Comment by betacanis** [comment]
Add the following javascript snippet to your rails template
```javascript
<script>
function onMercuryReady() { Mercury.saveUrl = '/pages/' + <%= @page.id %> +"/mercury_update"; };
</script>
```

**Comment by rkrevolution** [comment]
Where would this line go?  In a views page or in the .js file?

**Comment by betacanis** [comment]
You can inject this is the template (.erb) file directly. No need for .js file
