### ISSUE TITLE
mercury editor blank page in heroku

### ISSUE THREAD

**Issue by guille1194** [jejacks0n/mercury#482]
well, i have all the config of mercury editor including  config.assets.precompile += %w( mercury.js mercury.css mercury_overrides.css ) added in production.rb, and isn't working, only appears me a blank page, i am using rails 4, so any suggestion is appreciate it. :D

P.D. Sorry if i have any grammar error, normally i speak spanish. 

![1](https://cloud.githubusercontent.com/assets/13303286/9015579/b93eb4de-377e-11e5-88a3-c691430dd357.jpg)

**Comment by dmartinez05** [comment]
Hello. I am using mercury editor now, (April 2016) and I had the same error, I fixed only making reference to Jquery. Noticed that I using haml instead erb.

`/app/views/layout/mercury.html.haml
  %script{:crossorigin => "anonymous", :integrity => "sha256-fBiF7IYg9AoQ0EWUjT+fe4+cT3vS/x3ftIap8n6V4+M=", :src => "https://code.jquery.com/jquery-1.7.0.js"}       = javascript_include_tag 'jquery-1.7', 'mercury'`
