### ISSUE TITLE
Snippets with javascripts included

### ISSUE THREAD

**Issue by mediatainment** [jejacks0n/mercury#484]
Hi there, I am quite ready with my snippet implementation with an image dropzone. I am using dropzone.js. 

I have found out, that when I put javascript into the snippet it gets not rendered. 
The following code is placed in the ``options.html.erb`` but is not rendered in the dom. I dont know why.

**How can I fire an jQuery selector when the snippet is rendered?** 

```erb
<%= form_for 'options', {url: '/mercury/images', html: {multipart: true, class: 'dropzone form-horizontal', style: 'width:615px'}} do |f| %>
    <div class="fallback">
      <%= f.file_field :file, class: "span6 string optional" %>
    </div>
<% end %>

<script type="text/javascript" charset="utf-8">
$(this).ready(function () {
        $.getScript"/assets/dropzone.js", function () {
            console.log($(".dropzone"));

            $(".dropzone").dropzone({
                url: "/mercury/images",
                init: function () {
                    this.on("addedfile", function (file) {
                        alert("Added file.");
                    });
                    this.on("success", function (file, response) {
                        $('#options_image_id').val(response['image']['id']);
                    });
                }
            });
        });
    })

</script>
```

console log output:

    [prevObject: jQuery.fn.init[1], context: document, selector: ".dropzone"]

When I paste the same javascript code in the console, all works as expected and the console output is:

    [form.dropzone.form-horizontal, prevObject: jQuery.fn.jQuery.init[1], context: document, selector: ".dropzone"]

**Comment by jejacks0n** [comment]
I think it strips javascript.. and I doubt you want javascript in your content editable areas too. Put the javascript somewhere else, and call it when the snippet is added.
