### ISSUE TITLE
Section: Rails support in Readme.md?

### ISSUE THREAD

**Issue by 1c7** [jejacks0n/mercury#493]
mercury support Rails 5?
Rails 4?

Can you put a section in readme about the support rails version?

Thanks

**Comment by davidstosik** [comment]
👍

**Comment by mattlindsey** [comment]
Does this support Rails 5, and if not, will it ever?  I'm getting this with Rails 5.1.2:

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    mercury-rails was resolved to 0.9.0, which depends on
      coffee-rails (>= 3.2.2) was resolved to 4.2.2, which depends on
        railties (>= 4.0.0)
