### ISSUE TITLE
Neither install or post_install are working in Rails 5.2

### ISSUE THREAD

**Issue by Nmuta** [jejacks0n/mercury#500]
I imagine that this project may be deprecated by now , but just a heads up that following the READ ME with Rails 5.2 results in an unsuccessful install.   I found other complaining about this back in 2012 and they were directed to follow the POST_INSTALL instructions but these instructions don't seem to be up to date anymore either. Just a heads up. 

appears to be some routing issues amongst other things: 

> rails generate mercury:install       

/Users/my_stuff/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/mapper.rb:81:in `check_via': You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (ArgumentError)

**Comment by Nmuta** [comment]
Just re-read the developer notes and I didn't realize that this was a Rails 3 project and is no longer maintained. I fully understand how much work it is to maintain a project of this size with zero compensation or donations, so much respect for the work that went into this. I'll keep shopping. Thanks  !

**Comment by jejacks0n** [comment]
=) Yeah, it's crazy hard to keep up with contenteditable technology. There are some great libraries from the Guardian -- check out http://guardian.github.io/scribe/

There are whole teams of people who do it now, and maybe some day when it seems like there are fewer differences between the browser vendors I'll revisit some of this. There are some cool things like vue that would make this all so much easier too.

Thanks for the kind words, and best of luck!
