### ISSUE TITLE
mercury-rails should add itself to the asset.precompile list.

### ISSUE THREAD

**Issue by docwhat** [jejacks0n/mercury#73]
To make `mercury-rails` be precompiled I had to add this to `production.rb`:

```
config.assets.precompile += %w( mercury.js mercury.css mercury_overrides.css )
```

This should be done automatically by including the gem `mercury-rails`

See also: http://stackoverflow.com/questions/8056279/error-trying-use-mercury-wysiwyg-editor-in-rails-3-1-app-on-heroku

**Comment by rkrevolution** [comment]
this is still not working for us
